back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /back

user_interface:
    resource: "@UserInterfaceBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
