user_interface_homepage:
    path:     /
    defaults: { _controller: UserInterfaceBundle:Default:index}

signup:
    path:     /inscription
    defaults: { _controller: UserInterfaceBundle:Signup:signup }

signin:
    path:     /connection
    defaults: { _controller: UserInterfaceBundle:Signin:Signin }

login_check:
    pattern:   /user/login_check

logout:
    pattern:   /user/logout

payment:
    path:     /user/renouvellement-abonnement
    defaults: { _controller: UserInterfaceBundle:Payment:Payment }

payment_check:
    path:     /user/renouvellement-abonnement-soumission
    defaults: { _controller: UserInterfaceBundle:Payment:PaymentCheck }

card_check:
    path:     /user/verification-carte
    defaults: { _controller: UserInterfaceBundle:CardCheck:CardCheck }
