user_interface_homepage:
    path:     /
    defaults: { _controller: UserInterfaceBundle:Default:index}

signup:
    path:     /inscription
    defaults: { _controller: UserInterfaceBundle:Signup:signup }

signin:
    path:     /connection
    defaults: { _controller: UserInterfaceBundle:Signin:Signin }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

payment:
    path:     /user/renouvellement-abonnement
    defaults: { _controller: UserInterfaceBundle:Payment:Payment }

payment_check:
    path:     /user/renouvellement-abonnement-soumission
    defaults: { _controller: UserInterfaceBundle:Payment:PaymentCheck }

card_check:
    path:     /verification-carte
    defaults: { _controller: UserInterfaceBundle:CardCheck:CardCheck }

bills:
    path:     /user/factures
    defaults: { _controller: UserInterfaceBundle:Bill:Bills }

generate_pdf:
    path:     /user/generation-facture/{bill}
    defaults: { _controller: UserInterfaceBundle:Bill:Generate }
